# pandas_utils { #src.pandas_utils }

`pandas_utils`

Define utilities to work with DataFrames.

## Functions

| Name | Description |
| --- | --- |
| [highlight_conditionally](#src.pandas_utils.highlight_conditionally) | Highlight rows based on conditional match(es) in column. |
| [highlight_multiple_columns](#src.pandas_utils.highlight_multiple_columns) | Hilight multiple columns. |
| [highlight_multiple_columns_row_greater_than](#src.pandas_utils.highlight_multiple_columns_row_greater_than) | . |
| [highlight_multiple_columns_ver2](#src.pandas_utils.highlight_multiple_columns_ver2) | . |
| [highlight_unequal_columns](#src.pandas_utils.highlight_unequal_columns) | Hilight rows based on column inequality condition. |
| [show_df](#src.pandas_utils.show_df) | Show DataFrame with a summary in multi-row header. |
| [show_nans_dtypes_nunique](#src.pandas_utils.show_nans_dtypes_nunique) | Summarize missing values, datatypes and number of unique values in header. |

### highlight_conditionally { #src.pandas_utils.highlight_conditionally }

`pandas_utils.highlight_conditionally(df, col='check', value=False)`

Highlight rows based on conditional match(es) in column.

### highlight_multiple_columns { #src.pandas_utils.highlight_multiple_columns }

`pandas_utils.highlight_multiple_columns(col)`

Hilight multiple columns.

### highlight_multiple_columns_row_greater_than { #src.pandas_utils.highlight_multiple_columns_row_greater_than }

`pandas_utils.highlight_multiple_columns_row_greater_than(df, cols_to_check)`

.

### highlight_multiple_columns_ver2 { #src.pandas_utils.highlight_multiple_columns_ver2 }

`pandas_utils.highlight_multiple_columns_ver2(df, columns)`

.

### highlight_unequal_columns { #src.pandas_utils.highlight_unequal_columns }

`pandas_utils.highlight_unequal_columns(row, left_col, right_col)`

Hilight rows based on column inequality condition.

### show_df { #src.pandas_utils.show_df }

`pandas_utils.show_df(df)`

Show DataFrame with a summary in multi-row header.

#### Parameters

| Name   | Type                    | Description           | Default    |
|--------|-------------------------|-----------------------|------------|
| `df`   | pandas.pandas.DataFrame | dataframe to be shown | _required_ |

### show_nans_dtypes_nunique { #src.pandas_utils.show_nans_dtypes_nunique }

`pandas_utils.show_nans_dtypes_nunique(df, show_transpose=False)`

Summarize missing values, datatypes and number of unique values in header.

#### Parameters

| Name             | Type                    | Description                                             | Default    |
|------------------|-------------------------|---------------------------------------------------------|------------|
| `df`             | pandas.pandas.DataFrame | dataframe to be summarized                              | _required_ |
| `show_transpose` | bool                    | whether to show a transpose of the summarized DataFrame | `False`    |
