name: eda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip==24.0
  - pip:
    - Jinja2==3.1.3
    - requests==2.31.0
    - watermark==2.4.3
    - contexttimer==0.3.3
    - tqdm==4.66.2
    - vl-convert-python==1.3.0
    - altair==5.2.0
    - folium==0.16.0
  - conda:
    - ipykernel==6.29.3
    - gcc==13.2.0
    - fiona
    - rtree
    - pyproj
    - shapely
    - geopandas
    - python-duckdb==0.10.0
    - duckdb-engine==0.11.2
    - pyarrow==15.0.1
    - pandas==2.2.1
